import = [
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
    # "~/.config/alacritty/themes/themes/hyper.toml"
    # "~/.config/alacritty/themes/themes/rose-pine.toml"
    # "~/.config/alacritty/themes/themes/solarized_light.toml"
    # "~/.config/alacritty/themes/themes/solarized_dark.toml"
    # "~/.config/alacritty/themes/themes/solarized_osaka.toml"
    # "~/.config/alacritty/themes/themes/seashells.toml"
    # "~/.config/alacritty/themes/themes/alabaster.toml"
    # "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]

[shell]
program = "/bin/zsh"

[window]
# opacity = 0.98
# padding = { x = 5, y = 5 }
# decorations = "None"

[font]
size = 8
# normal = { family = "JetBrainsMono Nerd Font" }
# normal = { family = "MesloLGL Nerd Font" }
# normal = { family = "Ubuntu Mono" }
# normal = { family = "Iosevka Nerd Font" }
normal = { family = "FiraCode Nerd Font" }

[keyboard]
bindings = [
    { key="F11", action="ToggleFullscreen" }
]
