import = ["/home/wasabi/dotfiles/.config/alacritty/themes/themes/rose-pine.toml"]

[shell]
program = "/bin/zsh"

[window]
# opacity = 0.90
padding = { x = 0, y = 0 }
dynamic_padding = true
# decorations = "None"

[font]
# offset = { x = 0 , y = 10 }
size = 10
# normal = { family = "JetBrainsMono Nerd Font" }
# normal = { family = "MesloLGL Nerd Font" }
# normal = { family = "UbuntuMono Nerd Font" }
# normal = { family = "Iosevka Nerd Font" }
normal = { family = "FiraCode Nerd Font" }
# normal = { family = "RobotoMono Nerd Font" }
# normal = { family = "Liberation Mono" }
# normal = { family = "DankMono Nerd Font" }
# normal = { family = "SFMono Nerd Font" }
# normal = { family = "Monaco Nerd Font Mono" }
# normal = { family = "Inconsolata Nerd Font Mono" }

[keyboard]
bindings = [
    { key="F11", action="ToggleFullscreen" }
]
