import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[shell]
program = "/bin/zsh"

[window]
opacity = 0.98
padding = { x = 5, y = 5 }
# decorations = "None"

[font]
size = 10
normal = { family = "JetBrainsMono Nerd Font" }
# normal = { family = "MesloLGLDZ Nerd Font" }
# normal = { family = "Ubuntu Mono" }

[keyboard]
bindings = [
    { key="F11", action="ToggleFullscreen" }
]
