import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[shell]
program = "/bin/zsh"

[window]
# opacity = 0.9
padding = { x = 10, y = 10 }
decorations = "None"

[font]
# normal = { family = "JetBrainsMono Nerd Font" }
# normal = { family = "MesloLGLDZ Nerd Font" }
normal = { family = "Ubuntu Mono" }
# size = 10
